# Generated by Django 5.2.4 on 2025-07-24 08:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='clothingitem',
            old_name='updated_at',
            new_name='update_at',
        ),
    ]
